# -*- encoding : utf-8 -*-
module ExchangeRatesGenerator
  # Generated using "rake currency:generate_currency_codes" from within the exchange-rates-generator gem.
  # Scraped from http://www.iso.org/iso/support/currency_codes_list-1.htm
  # These are utf-8 so ensure that you correctly setup the necessary encodings in your app
  module Currencies
    def self.get(code)
      return nil if RAW[noramalise_code(code)] == nil
      name, entity = RAW[noramalise_code(code)]
      Currency.new(noramalise_code(code).to_sym, name, entity)
    end

    def self.get_name(code)
      return nil if RAW[noramalise_code(code)] == nil
      RAW[noramalise_code(code)][0]
    end

    private

    def self.noramalise_code(code)
      code.to_s.upcase
    end

    RAW = {
          'AED' => ["Uae Dirham", ["United Arab Emirates"]],
          'AFN' => ["Afghani", ["Afghanistan"]],
          'ALL' => ["Lek", ["Albania"]],
          'AMD' => ["Armenian Dram", ["Armenia"]],
          'ANG' => ["Netherlands Antillian Guilder", ["Netherlands Antilles"]],
          'AOA' => ["Kwanza", ["Angola"]],
          'ARS' => ["Argentine Peso", ["Argentina"]],
          'AUD' => ["Australian Dollar", ["Australia", "Christmas Island", "Cocos (Keeling) Islands", "Heard Island And Mcdonald Islands", "Kiribati", "Nauru", "Norfolk Island", "Tuvalu"]],
          'AWG' => ["Aruban Guilder", ["Aruba"]],
          'AZN' => ["Azerbaijanian Manat", ["Azerbaijan"]],
          'BAM' => ["Convertible Marks", ["Bosnia And Herzegovina"]],
          'BBD' => ["Barbados Dollar", ["Barbados"]],
          'BDT' => ["Taka", ["Bangladesh"]],
          'BGN' => ["Bulgarian Lev", ["Bulgaria"]],
          'BHD' => ["Bahraini Dinar", ["Bahrain"]],
          'BIF' => ["Burundi Franc", ["Burundi"]],
          'BMD' => ["Bermudian Dollar (Customarily Known As Bermuda Dollar)", ["Bermuda"]],
          'BND' => ["Brunei Dollar", ["Brunei Darussalam"]],
          'BOB' => ["Boliviano", ["Bolivia"]],
          'BOV' => ["Mvdol", ["Bolivia"]],
          'BRL' => ["Brazilian Real", ["Brazil"]],
          'BSD' => ["Bahamian Dollar", ["Bahamas"]],
          'BTN' => ["Ngultrum", ["Bhutan"]],
          'BWP' => ["Pula", ["Botswana"]],
          'BYR' => ["Belarussian Ruble", ["Belarus"]],
          'BZD' => ["Belize Dollar", ["Belize"]],
          'CAD' => ["Canadian Dollar", ["Canada"]],
          'CDF' => ["Congolese Franc", ["Congo, The Democratic Republic Of"]],
          'CHE' => ["Wir Euro", ["Switzerland"]],
          'CHF' => ["Swiss Franc", ["Liechtenstein", "Switzerland"]],
          'CHW' => ["Wir Franc", ["Switzerland"]],
          'CLF' => ["Unidades De Fomento", ["Chile"]],
          'CLP' => ["Chilean Peso", ["Chile"]],
          'CNY' => ["Yuan Renminbi", ["China"]],
          'COP' => ["Colombian Peso", ["Colombia"]],
          'COU' => ["Unidad De Valor Real", ["Colombia"]],
          'CRC' => ["Costa Rican Colon", ["Costa Rica"]],
          'CUC' => ["Peso Convertible", ["Cuba"]],
          'CUP' => ["Cuban Peso", ["Cuba"]],
          'CVE' => ["Cape Verde Escudo", ["Cape Verde"]],
          'CZK' => ["Czech Koruna", ["Czech Republic"]],
          'DJF' => ["Djibouti Franc", ["Djibouti"]],
          'DKK' => ["Danish Krone", ["Denmark", "Faroe Islands", "Greenland"]],
          'DOP' => ["Dominican Peso", ["Dominican Republic"]],
          'DZD' => ["Algerian Dinar", ["Algeria"]],
          'EEK' => ["Kroon", ["Estonia"]],
          'EGP' => ["Egyptian Pound", ["Egypt"]],
          'ERN' => ["Nakfa", ["Eritrea"]],
          'ETB' => ["Ethiopian Birr", ["Ethiopia"]],
          'EUR' => ["Euro", ["Åland Islands", "Andorra", "Austria", "Belgium", "Cyprus", "Finland", "France", "French Guiana", "French Southern Territories", "Germany", "Greece", "Guadeloupe", "Holy See (Vatican City State)", "Ireland", "Italy", "Luxembourg", "Malta", "Martinique", "Mayotte", "Monaco", "Montenegro", "Netherlands", "Portugal", "RÉunion", "Saint-BarthÉlemy", "Saint Martin", "Saint Pierre And Miquelon", "San Marino", "Slovakia", "Slovenia", "Spain", "Vatican City State (Holy See)"]],
          'FJD' => ["Fiji Dollar", ["Fiji"]],
          'FKP' => ["Falkland Islands Pound", ["Falkland Islands (Malvinas)"]],
          'GBP' => ["Pound Sterling", ["Guernsey", "Isle Of Man", "Jersey", "United Kingdom"]],
          'GEL' => ["Lari", ["Georgia"]],
          'GHS' => ["Cedi", ["Ghana"]],
          'GIP' => ["Gibraltar Pound", ["Gibraltar"]],
          'GMD' => ["Dalasi", ["Gambia"]],
          'GNF' => ["Guinea Franc", ["Guinea"]],
          'GTQ' => ["Quetzal", ["Guatemala"]],
          'GYD' => ["Guyana Dollar", ["Guyana"]],
          'HKD' => ["Hong Kong Dollar", ["Hong Kong"]],
          'HNL' => ["Lempira", ["Honduras"]],
          'HRK' => ["Croatian Kuna", ["Croatia"]],
          'HTG' => ["Gourde", ["Haiti"]],
          'HUF' => ["Forint", ["Hungary"]],
          'IDR' => ["Rupiah", ["Indonesia"]],
          'ILS' => ["New Israeli Sheqel", ["Israel"]],
          'INR' => ["Indian Rupee", ["Bhutan", "India"]],
          'IQD' => ["Iraqi Dinar", ["Iraq"]],
          'IRR' => ["Iranian Rial", ["Iran, Islamic Republic Of"]],
          'ISK' => ["Iceland Krona", ["Iceland"]],
          'JMD' => ["Jamaican Dollar", ["Jamaica"]],
          'JOD' => ["Jordanian Dinar", ["Jordan"]],
          'JPY' => ["Yen", ["Japan"]],
          'KES' => ["Kenyan Shilling", ["Kenya"]],
          'KGS' => ["Som", ["Kyrgyzstan"]],
          'KHR' => ["Riel", ["Cambodia"]],
          'KMF' => ["Comoro Franc", ["Comoros"]],
          'KPW' => ["North Korean Won", ["Korea, Democratic People's Republic Of"]],
          'KRW' => ["Won", ["Korea, Republic Of"]],
          'KWD' => ["Kuwaiti Dinar", ["Kuwait"]],
          'KYD' => ["Cayman Islands Dollar", ["Cayman Islands"]],
          'KZT' => ["Tenge", ["Kazakhstan"]],
          'LAK' => ["Kip", ["Lao People's Democratic Republic"]],
          'LBP' => ["Lebanese Pound", ["Lebanon"]],
          'LKR' => ["Sri Lanka Rupee", ["Sri Lanka"]],
          'LRD' => ["Liberian Dollar", ["Liberia"]],
          'LSL' => ["Loti", ["Lesotho"]],
          'LTL' => ["Lithuanian Litas", ["Lithuania"]],
          'LVL' => ["Latvian Lats", ["Latvia"]],
          'LYD' => ["Libyan Dinar", ["Libyan Arab Jamahiriya"]],
          'MAD' => ["Moroccan Dirham", ["Morocco", "Western Sahara"]],
          'MDL' => ["Moldovan Leu", ["Moldova, Republic Of"]],
          'MGA' => ["Malagasy Ariary", ["Madagascar"]],
          'MKD' => ["Denar", ["Macedonia, The Former Yugoslav Republic Of"]],
          'MMK' => ["Kyat", ["Myanmar"]],
          'MNT' => ["Tugrik", ["Mongolia"]],
          'MOP' => ["Pataca", ["Macao"]],
          'MRO' => ["Ouguiya", ["Mauritania"]],
          'MUR' => ["Mauritius Rupee", ["Mauritius"]],
          'MVR' => ["Rufiyaa", ["Maldives"]],
          'MWK' => ["Kwacha", ["Malawi"]],
          'MXN' => ["Mexican Peso", ["Mexico"]],
          'MXV' => ["Mexican Unidad De Inversion (Udi)", ["Mexico"]],
          'MYR' => ["Malaysian Ringgit", ["Malaysia"]],
          'MZN' => ["Metical", ["Mozambique"]],
          'NAD' => ["Namibia Dollar", ["Namibia"]],
          'NGN' => ["Naira", ["Nigeria"]],
          'NIO' => ["Cordoba Oro", ["Nicaragua"]],
          'NOK' => ["Norwegian Krone", ["Bouvet Island", "Norway", "Svalbard And Jan Mayen"]],
          'NPR' => ["Nepalese Rupee", ["Nepal"]],
          'NZD' => ["New Zealand Dollar", ["Cook Islands", "New Zealand", "Niue", "Pitcairn", "Tokelau"]],
          'OMR' => ["Rial Omani", ["Oman"]],
          'PAB' => ["Balboa", ["Panama"]],
          'PEN' => ["Nuevo Sol", ["Peru"]],
          'PGK' => ["Kina", ["Papua New Guinea"]],
          'PHP' => ["Philippine Peso", ["Philippines"]],
          'PKR' => ["Pakistan Rupee", ["Pakistan"]],
          'PLN' => ["Zloty", ["Poland"]],
          'PYG' => ["Guarani", ["Paraguay"]],
          'QAR' => ["Qatari Rial", ["Qatar"]],
          'RON' => ["New Leu", ["Romania"]],
          'RSD' => ["Serbian Dinar", ["Serbia"]],
          'RUB' => ["Russian Ruble", ["Russian Federation"]],
          'RWF' => ["Rwanda Franc", ["Rwanda"]],
          'SAR' => ["Saudi Riyal", ["Saudi Arabia"]],
          'SBD' => ["Solomon Islands Dollar", ["Solomon Islands"]],
          'SCR' => ["Seychelles Rupee", ["Seychelles"]],
          'SDG' => ["Sudanese Pound", ["Sudan"]],
          'SEK' => ["Swedish Krona", ["Sweden"]],
          'SGD' => ["Singapore Dollar", ["Singapore"]],
          'SHP' => ["Saint Helena Pound", ["Saint Helena, Ascension And Tristan Da Cunha"]],
          'SLL' => ["Leone", ["Sierra Leone"]],
          'SOS' => ["Somali Shilling", ["Somalia"]],
          'SRD' => ["Surinam Dollar", ["Suriname"]],
          'STD' => ["Dobra", ["SÃo Tome And Principe"]],
          'SVC' => ["El Salvador Colon", ["El Salvador"]],
          'SYP' => ["Syrian Pound", ["Syrian Arab Republic"]],
          'SZL' => ["Lilangeni", ["Swaziland"]],
          'THB' => ["Baht", ["Thailand"]],
          'TJS' => ["Somoni", ["Tajikistan"]],
          'TMT' => ["Manat", ["Turkmenistan"]],
          'TND' => ["Tunisian Dinar", ["Tunisia"]],
          'TOP' => ["Pa'anga", ["Tonga"]],
          'TRY' => ["Turkish Lira", ["Turkey"]],
          'TTD' => ["Trinidad And Tobago Dollar", ["Trinidad And Tobago"]],
          'TWD' => ["New Taiwan Dollar", ["Taiwan, Province Of China"]],
          'TZS' => ["Tanzanian Shilling", ["Tanzania, United Republic Of"]],
          'UAH' => ["Hryvnia", ["Ukraine"]],
          'UGX' => ["Uganda Shilling", ["Uganda"]],
          'USD' => ["Us Dollar", ["American Samoa", "British Indian Ocean Territory", "Ecuador", "El Salvador", "Guam", "Haiti", "Marshall Islands", "Micronesia, Federated States Of", "Northern Mariana Islands", "Palau", "Panama", "Puerto Rico", "Timor-Leste", "Turks And Caicos Islands", "United States", "United States Minor Outlying Islands", "Virgin Islands (British)", "Virgin Islands (U.S.)"]],
          'USN' => ["Us Dollar (Next Day)", ["United States"]],
          'USS' => ["Us Dollar (Same Day)", ["United States"]],
          'UYI' => ["Uruguay Peso En Unidades Indexadas", ["Uruguay"]],
          'UYU' => ["Peso Uruguayo", ["Uruguay"]],
          'UZS' => ["Uzbekistan Sum", ["Uzbekistan"]],
          'VEF' => ["Bolivar Fuerte", ["Venezuela"]],
          'VND' => ["Dong", ["Viet Nam"]],
          'VUV' => ["Vatu", ["Vanuatu"]],
          'WST' => ["Tala", ["Samoa"]],
          'XAF' => ["Cfa Franc Beac", ["Cameroon", "Central African Republic", "Chad", "Congo", "Equatorial Guinea", "Gabon"]],
          'XAG' => ["Silver", [" "]],
          'XAU' => ["Gold", ["Entity Not Applicable"]],
          'XBA' => ["Bond Markets Units European Composite Unit (Eurco)", [" "]],
          'XBB' => ["European Monetary Unit (E.M.U.-6)", [" "]],
          'XBC' => ["European Unit Of Account 9(E.U.A.-9)", [" "]],
          'XBD' => ["European Unit Of Account 17(E.U.A.-17)", [" "]],
          'XCD' => ["East Caribbean Dollar", ["Anguilla", "Antigua And Barbuda", "Dominica", "Grenada", "Montserrat", "Saint Kitts And Nevis", "Saint Lucia", "Saint Vincent And The Grenadines"]],
          'XDR' => ["Sdr", ["International Monetary Fund (I.M.F)"]],
          'XFU' => ["Uic-Franc", [" "]],
          'XOF' => ["Cfa Franc Bceao", ["Benin", "Burkina Faso", "CÔte D'ivoire", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo"]],
          'XPD' => ["Palladium", [" "]],
          'XPF' => ["Cfp Franc", ["French Polynesia", "New Caledonia", "Wallis And Futuna"]],
          'XPT' => ["Platinum", [" "]],
          'XTS' => ["Codes Specifically Reserved For Testing Purposes", [" "]],
          'XXX' => ["The Codes Assigned For Transactions Where No Currency Is Involved Are:", [" "]],
          'YER' => ["Yemeni Rial", ["Yemen"]],
          'ZAR' => ["Rand", ["Lesotho", "Namibia", "South Africa"]],
          'ZMK' => ["Zambian Kwacha", ["Zambia"]],
          'ZWL' => ["Zimbabwe Dollar", ["Zimbabwe"]],
          ' ' => ["No Universal Currency", ["Antarctica", " "]]
    }.freeze

  end # module Currencies
end # module ExchangeRatesGenerator
