module ExchangeRatesGenerator
  module Formatters
    class Javascript < Base
      def initialize(currency, rates)
        super(currency, rates)
      end

      def default_extension
        self.class.default_extension
      end

      def description
        self.class.description
      end

      class << self
        def default_extension
          :js
        end

        def description
          "Javascript Formatter"
        end
      end

      protected

      def formatter_classname
        @formatter_classname ||= Extlib::Inflection.underscore(@currency.to_s)
      end

      def header
        <<-EOS
//
// THIS FILE IS AUTOMATICALLY GENERATED USING THE exchange-rates-generator RUBY GEM DO NOT EDIT IT.
//

if ( typeof(exchange_rates) === 'undefined' ) {
  var exchange_rates = {};
}

// This Library provides exchange rate conversion from #{@currency.to_s} to various other currencies. The list of
// currencies that this Library can convert to can be retrieve using the supported_currencies method.
//
// Generated using the exchange-rates-generator Ruby Gem.
exchange_rates.#{formatter_classname} = function() {
        EOS
      end

      def body
        <<-EOS
  return {
    base_currency : function() {
      return '#{@currency.to_s}';
    },

    supported_currencies : function() {
      return [
#{rates.keys.collect {|c| "        \"#{c}\"" }.join(",\n") }
      ];
    },

    get : function(target_currency) {
      return this.rates()[target_currency.toUpperCase()];
    },

    convert : function(amount, target_currency) {
      var rate = this.get(target_currency);
      if ( !rate ) {
        throw "This exchange rate converter can not convert to " + target_currency;
      }
  
      return rate * parseFloat(amount, 10);
    },

    rates : function() {
      return {
        "#{@currency.to_s}"    : 1.0,
#{rates.to_a.collect { |rate| "        \"#{rate[0].to_s}\"    : #{rate[1].to_s}" }.join(",\n")}
      }
    }

  };
        EOS
      end

      def footer
        <<-EOS
}();
EOS
      end
    end
  end # module Formatters
end # module ExchangeRatesGenerator